name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read

        strategy:
            matrix:
                node-version: [25.x]

        steps:
            - uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: bun install --frozen-lockfile
            - run: bun run build
